version: "3.6"
services:
  home_base:
    build:
      context: ./home_base
  home:
    container_name: home
    restart: always
    privileged: true
    build:
      context: ./home
      args:
        branchname: grow_monitor
        cfgfilename: grow_monitor
    logging:
      options:
        max-size: "1m"
        max-file: "3"
  home_grow:
    container_name: home_grow
    restart: always
    privileged: true
    ports:
      - 1883
#    volumes:
#      - D:\home:/home_volumes
    build:
      context: ./home_grow
      args:
        branchname: master
        cfgfilefolder: pigrowtent
        cfgfilename: grow_tent
    logging:
      options:
        max-size: "1m"
        max-file: "3"
