version: "3.6"
services:
  home:
    container_name: home
    restart: always
    privileged: true
    build:
      context: ./home
      args:
        branchname: docker
        cfgfilename: env000.json
