version: "3.6"
services:
  home:
    container_name: home
    restart: always
    privileged: true
    build:
      context: ./home
      args:
        branchname: typehints
        cfgfilename: env005
    logging:
      options:
        max-size: "1m"
        max-file: "3"
